### ISSUE TITLE
$query->count() doesn't return the correct count.

### ISSUE THREAD

**Issue by burzum** [cakephp/elastic-search#103]
``` php
        debug($countQuery->all()->getTotalHits());
        $profilesCount = ($countQuery->count());
        debug($profilesCount);
```

First debug will give you a different number than second. Except you have the same counts ;)

I expected `$countQuery->count()` to return the same number as `getTotalHits()`.

While I'm OK with using getTotalHits() after I found the method I don't think the behavior of count() is correct.

**Comment by markstory** [comment]
The [Query object doesn't implement count](https://github.com/cakephp/elastic-search/blob/master/src/Query.php) are you sure you're not calling `count()` on the resultset?  The documentation for `ResultSet::count()` states:

> Returns size of current set

Which means its not supposed to be the same as `getTotalHits()`
