### ISSUE TITLE
example with association

### ISSUE THREAD

**Issue by plalanne** [cakephp/elastic-search#104]
Hi
i really don't understand the documentation of the elasticsearch plugin in the cookbook.
Is it possible to have an example (like a blog) with associated tables (belongsTo and belongtsToMany) and this plugin and maybe with a search in articles

Thanks

**Comment by lorenzo** [comment]
There are no associations in this plugin, as ElasticSearch is a document storage. Do you understand what elastic search is about?

**Comment by plalanne** [comment]
yes i understand elasticseach, it's not my probleme. But i d'ont understand how to implement it in cakephp 3.
The example in the cookbook is not very explicit. It's the reason why i'm looking for an example like a blog

**Comment by markstory** [comment]
You can't make associations in elastic search, which is why its not in the docs. If you need relational data, you should avoid elastic search.
