### ISSUE TITLE
failed to parse error (id)

### ISSUE THREAD

**Issue by lilHermit** [cakephp/elastic-search#105]
If I pull a record from ES and edit it all is fine, however if I create a new entity save it, modify it and resave I get "failed to parse". From my debugging I believe https://github.com/cakephp/elastic-search/blob/master/src/Type.php#L473 should read "unset($data['id']);"

working example (fetch and save)

<pre>$menuItemType = TypeRegistry::get('MenuItems');

$menuItem = $menuItemType->find()->firstOrFail();
$menuItem->content = "changed content";
$menuItemType->save($menuItem);</pre>

Failing example (new, save and resave)

<pre>$menuItemType = TypeRegistry::get('MenuItems');
$menuItem = $menuItemType->newEntity();
$menuItem->action = 'Do something';
$menuItemType->save($menuItem);

$menuItem->content = 'Some content';
$menuItemType->save($menuItem);</pre>

**Comment by lilHermit** [comment]
On further investigation it is the double save causes the Exception too

<pre>$menuItemType = TypeRegistry::get('MenuItems');
$menuItem = $menuItemType->find()->firstOrFail();
$menuItem->content = "changed content";
$menuItemType->save($menuItem);
$menuItemType->save($menuItem);
<pre>

**Comment by lilHermit** [comment]
The issue does seem to be caused by meta values like `id` and `_version` in the body of the PUT request

**Comment by markstory** [comment]
Closing as a pull request is open now.
