### ISSUE TITLE
Controller does not exist yet in beforeDispatch with PSR7?

### ISSUE THREAD

**Issue by nickygerritsen** [cakephp/elastic-search#109]
It seems the controller does not exist yet when 'Dispatcher.beforeDispatch' is dispatched, resulting in the Elastic Type Registry not being registered.

See also https://github.com/cakephp/cakephp/blob/3.3.6/src/Http/ActionDispatcher.php#L81: here you can see the controller is only created later on.

For now I have fixed this in my own bootstrap.php by binding on `Dispatcher.invokeController` and doing the exact same code, but this doesn't seem the way to go for me. I think something should be fixed, either by doing this binding on `Dispatcher.invokeController` in this plugin or by doing something different, like creating the controller in the `Dispatcher.beforeDispatch` call. Both options sound ugly to me, but maybe someone can think of a better way.

**Comment by markstory** [comment]
Binding to `Dispatcher.invokeController` or augmenting the event listeners to be middleware might be another good option.

**Comment by nickygerritsen** [comment]
I think doing it in the middleware still doesn't give us the actual controller right? Because that is only created in the dispatcher, which is in the last middleware, i.e. the app itself.

**Comment by markstory** [comment]
If the middleware is inserted *after* the ControllerFactory, we should have access to the controller. Another option is to use `Controller.initialize`, but that will mean you can't use ES models in initialize().

**Comment by markstory** [comment]
Pull request up now.
