### ISSUE TITLE
Update ruflin/elastica dependency to 5.0.0

### ISSUE THREAD

**Issue by lilHermit** [cakephp/elastic-search#111]
The latest version of ES doesn't require a delete_by_query plugin the functionality is now in core and the query has changed from DELETE /type/_query_ to POST /type/_delete_by_query

ruflin/elastica 5.0.0 has this change

**Comment by markstory** [comment]
The significant breaks in ruflin/elastica have made the last few upgrades hard :cry:

**Comment by lilHermit** [comment]
Yeah the top of BoolFilter in 3.2.3 is worrying ;-)

https://github.com/ruflin/Elastica/blob/3.2.3/lib/Elastica/Filter/BoolFilter.php

Seems like elastic-search needs substantial changes #movinggoalposts

**Comment by josegonzalez** [comment]
@lilHermit if you're interested in working on this, we'd love a pull request :)

**Comment by lilHermit** [comment]
@josegonzalez I was thinking of doing exactly that. I'll create a 5.0 branch locally and get started

**Comment by josegonzalez** [comment]
<3
