### ISSUE TITLE
This plugin is not working with latest version 5.1.1

### ISSUE THREAD

**Issue by addressmax** [cakephp/elastic-search#116]
I updated with composer, but I am getting errors in querying. Errors in Elastica. It's downloading 2.2 version but 5.0 is needed for Latest Elastic Search Version.
How should I update it.

**Comment by markstory** [comment]
>  How should I update it.

One of the challenges is that elastica 5 contains a number of backwards incompatible changes that cause this plugin to break. Right now the `1.0` branch might work, as it uses elastica 3.

**Comment by lorenzo** [comment]
Branch 1.0 does work with elastic 5

**Comment by lorenzo** [comment]
I'll try to merge that branch into master this weekend and add a few improvements

**Comment by addressmax** [comment]
lorenzo is there any update on this issue. We are stuck with the development.
Please do this ASAP.

**Comment by josegonzalez** [comment]
@addressmax When @lorenzo has time to perform the work, he will get to it. We are all unpaid volunteers on CakePHP, and thus we expect some amount of patience from our users. Being rude is a sure way to discourage our open source work.

Thanks for waiting.

**Comment by markstory** [comment]
Also you can depend on the head of the `1.0-dev` branch in the mean time.
