### ISSUE TITLE
Error in response exception

### ISSUE THREAD

**Issue by jubbs** [cakephp/elastic-search#124]
Found an error in the reponse exception class. Needed to change to the following. Not really sure how to use github so just posting it here

    public function __construct(Request $request, Response $response)
    {
        $this->_request = $request;
        $this->_response = $response;
	$error = $response->getError();
        parent::__construct($error['reason']);
    }

**Comment by markstory** [comment]
Which file is that function supposed to be updated in?

**Comment by jubbs** [comment]
Apologies.

I was using the wrong version of elastic search (5.3) downgraded to 2.3 and no longer an issue.

Thanks
