### ISSUE TITLE
index_not_found_exception

### ISSUE THREAD

**Issue by dornellas13** [cakephp/elastic-search#130]
Hi guys im using the plugin "cakephp/elastic-search": "dev-master" with version  5.5.1 of elastic search, Im install elastic search with home brew on mac and I made all configurations and installations according to the tutorial of cookbook, However, when i try mapping my entity "Categorias"  i receive one wrong message with  "Wrong parameters for Elastica\Exception\ResponseException". Then I went to check if the elastic was creating the "my_apps_index" in http://localhost:9200/my_apps_index and i receive the message " index_not_found_exception status 404", i want know how i can solve this problem. Can someone help me?

Best regards,
Marcos dornellas

Below are the photos with the problems.

<img width="1280" alt="captura de tela 2017-08-13 as 14 03 09" src="https://user-images.githubusercontent.com/12344282/29251707-511d8b62-8030-11e7-9624-18f74dd75faa.png">
<img width="1280" alt="captura de tela 2017-08-13 as 14 02 42" src="https://user-images.githubusercontent.com/12344282/29251709-54262e86-8030-11e7-81ee-dd8612d5edbc.png">
<img width="1280" alt="captura de tela 2017-08-13 as 14 02 24" src="https://user-images.githubusercontent.com/12344282/29251710-5692d78c-8030-11e7-8e3e-3d60220894fa.png">

**Comment by markstory** [comment]
Have you tried creating the index that is missing?

**Comment by dornellas13** [comment]
Hummm I'm understand, but i don't know how to do this, Can you explain better please?

**Comment by markstory** [comment]
Elastic Search indicies [need to be created](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html) through the HTTP interface generally.

**Comment by dornellas13** [comment]
Cool but i don't understand Any thing, when i start with this plugin and im work with elastic version 5.4, when i came in http://localhost:9200/my_apps_index the mapping has been done automatically i guess and  yesterday i updated the elastic and this problem appeared, there is no way mapping can to occur automatically?

**Comment by markstory** [comment]
> there is no way mapping can to occur automatically

Elasticsearch can infer mappings based on the first indexed document. In my experience it is best to define your mappings manually as Elasticsearch can only infer so much about documents being indexed.

**Comment by dornellas13** [comment]
Thank you markstory,  I'm trying do this, mapping my entitys in elastic, however, i don't have much experience with him, If i have problem, you can help me? How can i talk to you, here?

**Comment by lorenzo** [comment]
You can get help in the clack channel http://cakesf.herokuapp.com
