### ISSUE TITLE
Where don't work.

### ISSUE THREAD

**Issue by dornellas13** [cakephp/elastic-search#131]
Hello guys, 
Someone can help me? i have an mapping call doacoes and i did  a query with a basic condition with "where" but i receive a wrong response "Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]])". I only get wrong message when i use condition "where", however, when  i use $doacao = $this->Doacoes->find(), it works perfectly. 

With condition "WHERE"!
<img width="716" alt="captura de tela 2017-08-20 as 17 24 11" src="https://user-images.githubusercontent.com/12344282/29498151-8c043536-85cc-11e7-90da-efef7851b486.png">
<img width="1280" alt="captura de tela 2017-08-20 as 17 29 20" src="https://user-images.githubusercontent.com/12344282/29498200-6b971772-85cd-11e7-9614-8185792f08ec.png">

Without condition "WHERE"!

<img width="423" alt="captura de tela 2017-08-20 as 17 24 27" src="https://user-images.githubusercontent.com/12344282/29498169-cbda81ba-85cc-11e7-8e2e-3b0a0856745a.png">
<img width="1180" alt="captura de tela 2017-08-20 as 17 24 37" src="https://user-images.githubusercontent.com/12344282/29498171-d18d853a-85cc-11e7-8b2b-c17addd1fd95.png">

**Comment by lorenzo** [comment]
What version of this plugin are you using? and what version of elastic search?

If you use Elastic search >= 2.0, then you need to use the `1.0` branch of this plugin

**Comment by dornellas13** [comment]
Hi @lorenzo so im working with this plugin in version "dev-master" and elasticsearch 5.5, apparently it's all right, Would you have another option?

**Comment by lorenzo** [comment]
Try `"cakephp/elastic-search": "1.*"` in your composer.json

**Comment by dornellas13** [comment]
It Worked, thank you @lorenzo. However, im try make an query with clause "LIKE" and it is not working, you can do an example of query using "LIKE" please?

**Comment by lorenzo** [comment]
@dornellas13 you will have to read the elastic documentation, there are many valid answers to your question, each of them with different characteristics. 

You could start with

```php
$query->where(function ($builder) {
    return $builder->simpleQuerySTring('my_field', 'search this');
})`

**Comment by dornellas13** [comment]
Thank you @lorenzo.
