### ISSUE TITLE
Refresh Document

### ISSUE THREAD

**Issue by dornellas13** [cakephp/elastic-search#136]
Hi guys, I have a problem with insert or update of a document, when i insert a new row in document and redirect to my index the new row don't appear, however when a press ctr+F5 the row appear, i searched in document of elastic search and find an method call "refresh", but i don't know apply this in cakephp with elastic search, someone can help me?

**Comment by markstory** [comment]
Sounds like you are bumping into the eventual consistency behavior that ElasticSearch has. You'd have to use the features of elastica to refresh the relevant indexes.

```php
$typeObject->connection()->getIndex()->refresh()
```

Should do the trick.
