### ISSUE TITLE
Amount of record allowed

### ISSUE THREAD

**Issue by dornellas13** [cakephp/elastic-search#137]
Hi guys i'm have a problem with amount of record that is appearing in my list, by default 10 records are appearing, I want know how i can increase this setting, someone can help me? Thanks.

**Comment by markstory** [comment]
You should be able to use the limit method to increase the number of records you get. https://github.com/cakephp/elastic-search/blob/ae3deeb81d64392afc4635cf623c89a3c8dca11d/src/Query.php#L131

**Comment by agarzon** [comment]
Hi @dornellas13 I just noticed I had the same issue. All queries are always limited to 10 records by default. I don't know why :unamused:

A select all, will be limited always to 10 records, but I know I have millions documented.
```php
$this->Tournaments->find()->all();
```
I tried 
```php
$this->Tournaments->find()->limit(500000)->all();
```

but elastic complained: 
```
Result window is too large, from + size must be less than or equal to: [10000] but was [500000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting. [reason: all shards failed]
```

So, this worked:

```php
$this->Tournaments->find()->limit(10000)->all();
```

Now I wonder, if the query is actually exploring all my records or is limited.

**Comment by agarzon** [comment]
Well, now I see 10000 is actually the elasticsearch default. 
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-request-from-size.html

I guess the plugin should use the same limit as build-in default allowing the developer to use limit if need less records.
