### ISSUE TITLE
[Question] deleteAll

### ISSUE THREAD

**Issue by allana-cloud** [cakephp/elastic-search#138]
Hi guys, how can i truncate all documents from type? deleteAll() is requiring me for a condition, I wanted the condition be like match_all: {}

Thanks

**Comment by markstory** [comment]
You should be able to pass an `AbstractFilter` instance as the conditions for `deleteAll()` allowing you to create a match_all query. I don't have an example handy, but from a quick read of the code it should work.

**Comment by allana-cloud** [comment]
Thanks markstory for your reply! example code would be pretty much handy :)
