### ISSUE TITLE
Adding new document. How to add id to _source

### ISSUE THREAD

**Issue by allana-cloud** [cakephp/elastic-search#139]
When adding a new document, I can see that you can specify the id from the entity. 
this then get set to _id in ES
can i also add the value/field **id** in my _source?

i.e
create a document with this info in ES $entity = ['id' => 2, 'name' => 'Account Name'];
 {
                "_index": "sample_index",
                "_type": "accounts",
                "_id": "2",
                "_score": 1,
                "_source": {
                    "name": "Account Name"
                }
}

is there a way where I can get this kind of document?
 {
                "_index": "sample_index",
                "_type": "accounts",
                "_id": "2",
                "_score": 1,
                "_source": {
                    **"id":  2,**
                    "name": "Account Name"
                }
}

**Comment by markstory** [comment]
I don't think there currently is a way to do that.
