### ISSUE TITLE
The above code has something wrong when querying into elastic search.

### ISSUE THREAD

**Issue by quang0212083** [cakephp/elastic-search#140]
Hi guys, please help me.
The above code has something wrong when querying into elastic search.

$model = 'Posts';
$conditions = [
      'product_name LIKE' => '%'.$keyword.'%'
];
$tbl = TypeRegistry::get($model);
$query = $tbl->find()->where($conditions);
return $query->toArray();

Thank so much.

**Comment by ravage84** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
