### ISSUE TITLE
Compatibility with ES 6.x ?

### ISSUE THREAD

**Issue by TheMiller2015** [cakephp/elastic-search#141]
Hello there!

I just discovered elasticsearch and the 1.0-plugin-branch. I installed the docker image of ES 6, installed the 1.0-plugin and just running into problems / exceptions. Is the current 1.0 (dev-master) compatible with ES 6? I'm trying to start a 5.1 image. Maybe, the problems are caused by myself - I never used ES before...

Thanks!

**Comment by markstory** [comment]
ES 6.0 is pretty new (it came out on nov 14) and has a number of breaking changes, we've not had the time to update this plugin to use newer client versions, so for now you'd be best to stick with elasticsearch 5.

**Comment by TheMiller2015** [comment]
Yes Mark, thanks for your answer. Didn't recognize that release date. But I tried ES 5 and it worked pretty fine. I started that version (thx to docker) - no problem.
But when we're talkin about new versions, ES 6 / 7...9 will not have the mappings or types (or whatever - just read this on their page). Is it save to use ES5 with cakephp3 and in the future to switch to ES7...9 with cake? Because we're developing a new system from the ground and want to be safe regarding conversions to new versions. Hope you know what I mean ;) thx.

**Comment by markstory** [comment]
> Is it save to use ES5 with cakephp3 and in the future to switch to ES7...9 with cake?

Yes. From what I understood of the mapping deprecation announcement you'll have an easier time upgrading if you have only one type per index as that is the direction ES is heading.

**Comment by TheMiller2015** [comment]
Helpful answer. Does this mean, I have to define multiple es-datasources in app.php because each one is set up with an index-name? (Sorry, but es is new to me.)

**Comment by markstory** [comment]
Yes, you would need multiple es datasources. This is not idea but the plugin was designed well before mapping types were deprecated. We'll probably need to revise the connection:index relation in a future release.

**Comment by TheMiller2015** [comment]
Ok thanks, no problem. I'll do so.
