### ISSUE TITLE
Removal of mapping types

### ISSUE THREAD

**Issue by qqqqb** [cakephp/elastic-search#144]
Elasticsearch moving forward on removing types and stay with single type for the index (As it should be). as it shows on schedule of removal of mapping types 

> Mapping types will be completely removed in Elasticsearch 7.0.0.
[https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types](url)

Noticing the parent/child relations will be mapped using **[Join Field](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html)**

My suggestion is to move forward with this update because on ES 8 type parameter will be no longer supported in URLs. What I did is adding field for each document **doc_type** and flag it as required for indexing using **Ingest Node**. And create Entity for each **doc_type** with conditions.

I'm ready to helps on this upgrade :)

**Comment by markstory** [comment]
Perhaps you could help with #143 which is aiming to solve this issue as well.
