### ISSUE TITLE
Basic Search Query

### ISSUE THREAD

**Issue by ystkmeg** [cakephp/elastic-search#146]
How do I build a query like below by find() method?
```
{
  "query": {
    "query_string": {
      "fields": ["title","body"],
      "query": "keyword1 keyword2"
    }
  }
}
```

If I write something like below in my controller,
```
$search_result = $this->ElasticArticles->find()
    ->where([
        'or' => [
            'title' => 'keyword1 keyword2',
            'body' => 'keyword1 keyword2'
        ]
    ]);
```

I get queries like this
```
"query" : {
    "bool" : {
        "filter" : [{
            "bool" : {
                "must" : [{
                    "bool" : {
                        "should" : [{ 
                            "term" : {
                                "title" : "keyword1 keyword2"
                             }
                          },
                          {
                              "term" : {
                                  "body" : "keyword1 keyword2" 
                               } 
                          }]
                       }
                   }]
               }
           }]
       }
    }
```

I would like to search indices by two keywords that match the contents of the title or the body.

I use elasticsearch6.2.2 and cakephp/elastic-search2.0 beta

Thanks in advance.

**Comment by lorenzo** [comment]
Use the QueryBuilder object as described here:

https://book.cakephp.org/3.0/en/elasticsearch.html#searching-indexed-documents

You can use, for example, the `simpleQueryString` method:

https://github.com/cakephp/elastic-search/blob/master/src/QueryBuilder.php#L437

**Comment by ystkmeg** [comment]
It worked as expected!
Thank you so much!
