### ISSUE TITLE
[Question] AWS ElasticSearch configuration

### ISSUE THREAD

**Issue by ystkmeg** [cakephp/elastic-search#147]
I know this is not an ask forum, but I don't find any clue in other platform...

I would like to know how to configure AWS ElasticSearch with this plugin.

This plugin uses Elastica to connect to ElasticSearch, so it should be possible to connect to AWS's one too, but I have no idea how to make it possible.

I use ElasticSearch 6.2 and cakephp/elastic-search 2.0.0-beta

Any help is sincerely appreciated.

**Comment by lorenzo** [comment]
How is AWS different to having a local elastic search server? You just need to indicate the host address and port

**Comment by markstory** [comment]
You connect to AWS elasticsearch just like any other elasticsearch instance as @lorenzo mentioned.

**Comment by ystkmeg** [comment]
It works when the port is 80, but I get 

> [Elastica\Exception\Connection\HttpException] Unknown error:52

when I put 443 as the port.
Is this an expected behavior or am I doing something wrong?


```
'elastic' => [
    'className' => 'Cake\ElasticSearch\Datasource\Connection',
    'driver' => 'Cake\ElasticSearch\Datasource\Connection',
    'host' => 'my-endpoint.my-region.es.amazonaws.com',
    'port' => 443, \\ works fine with 80
    'log' => true,
    'index' => 'my-index',
],
```

**Comment by ystkmeg** [comment]
And how do I configure the access to AWS Elastic Search with credentials?
It works when the AWS instance is open to public access, but I need to control access so the credentials(or signature?) are needed.

**Comment by markstory** [comment]
> ... but I need to control access so the credentials(or signature?) are needed.

You might be able to use `https://` on the host name to get a TLS connection, as for credentials, how are they sent in the HTTP requests to elasticsearch? I've used firewall rules in the past to keep elasticsearch separated from the public internet in AWS.

**Comment by CauanCabral** [comment]
That's a Elastica configuration question, but for what I found, you need to use transport **AwsAuthV4**, something like:

```php
'elastic' => [
    'className' => 'Cake\ElasticSearch\Datasource\Connection',
    'driver' => 'Cake\ElasticSearch\Datasource\Connection',
    'transport' => 'AwsAuthV4',
    'host' => 'https://my-endpoint.my-region.es.amazonaws.com',
    'log' => true,
],
```

Some resources:

 - In [that pull](https://github.com/ruflin/Elastica/pull/1056) you can see how AWS Credentials are supported.
 - API documents: http://elastica.io/api/latest/classes/Elastica.Transport.AwsAuthV4.html
 - That one is a similar wrapper for Symfony, with a sample configuration (the keys are the same for both): https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1151

**Comment by lorenzo** [comment]
Maybe that should be added to the book / README
