### ISSUE TITLE
setting name and type in index

### ISSUE THREAD

**Issue by EliasDeVos** [cakephp/elastic-search#150]
Hi,
I am working with the 2.0.0-beta tag.
Everything seems to be working except for when you want to change the name of a custom Index.

According to the docs you should be able to change the $name property.

But if i get an Index class with the IndexRegistry this property gets overwritten all the time,
https://github.com/cakephp/elastic-search/blob/master/src/IndexRegistry.php#L71
it is because of the following line, name always gets passed to the Index constructor.

At the moment i can fix this by passing the name in the options array with my IndexRegistry.

But it would be nicer to be able to change it once in the CustomIndex Class.

How would you fix this ? i can make a pull request for it if you want

**Comment by lorenzo** [comment]
I don't think the docs are intended to say that you are able to change the index name by using the `$name` property. Where did you see that? And what are you trying to do?

**Comment by EliasDeVos** [comment]
here in the readme https://github.com/cakephp/elastic-search/blob/master/README.md
Under defining an index class you have a $name and a $type variable,

i taught you could chance those and this would change them in your CustomIndex model

I have a CompaniesIndex but i don't want to map it on companies/companies/ but on customValue/companies

**Comment by lorenzo** [comment]
That's a mistake. I'll investigate how this came about and document the actual way of doing this

**Comment by lorenzo** [comment]
@EliasDeVos can you check the new README and see if that helps?

**Comment by EliasDeVos** [comment]
Oke, i have looked into the IndexRegistry::get method and i think right now the only way of changing the name is by passing options to the get method.
Otherwise he just uses this Inflector::underscore($classAlias) and the className gets used

Thanks for looking into it

**Comment by EliasDeVos** [comment]
Yes thx @lorenzo, you can close this issue

**Comment by lorenzo** [comment]
great!
