### ISSUE TITLE
cake 3.6 compatibility

### ISSUE THREAD

**Issue by EliasDeVos** [cakephp/elastic-search#151]
Hi, i was wondering when you guys are going to release a tag that is compatible with cake 3.6 or if i can help create pull requests for it.

right now i have the following issue in the 
https://github.com/cakephp/elastic-search/blob/master/config/bootstrap.php#L27
the subject() should be replaced with getSubject()

Can i make a pull request for the current master ?

**Comment by lorenzo** [comment]
yes, please send a pull request

**Comment by akalantari** [comment]
All instances of `errors`, `validator`, `source` and etc. must be replaced with the setter and getter functions.
Also in ElasticSearch 6.0, there's an error introduced by the description below
"Content-Type header [application/x-www-form-urlencoded] is not supported"
The solution is to use `application/json` as `Content-Type` header.

I made my fork and made the changes myself
