### ISSUE TITLE
(Question) saveMany

### ISSUE THREAD

**Issue by bumburoom** [cakephp/elastic-search#166]
is there some reason why the saveMany function from the Type.php class was deleted?

Thanks

**Comment by markstory** [comment]
It looks like it is still present in [Index](https://github.com/cakephp/elastic-search/blob/4b26f945273d69269e544c81e3b6f39d75299eec/src/Index.php#L638)

**Comment by bumburoom** [comment]
But not in the last release... How is it possible?

**Comment by bumburoom** [comment]
Oh well, the function has been moved... Thank you!

**Comment by bumburoom** [comment]
But the Index.php is not present in the last release, so right now is there no possibility to call saveMany function.

**Comment by saeideng** [comment]
this already exist 
https://github.com/cakephp/elastic-search/compare/1.0...d83f7a00e85815?expand=1

**Comment by saeideng** [comment]
> in the last stable release (1.5.1)

latest version now is 1.5.2 :)
https://github.com/cakephp/elastic-search/releases/tag/1.5.2
