### ISSUE TITLE
Unknown method "getRepository"

### ISSUE THREAD

**Issue by agarzon** [cakephp/elastic-search#170]
Just updated this plugin via composer from 1.0 to 1.5 and everything broke.

I get: 
```Unknown method "getRepository"```

I had to return to 1.0 and everything works again.

Running cakephp 3.5

**Comment by saeideng** [comment]
`getRepository` added in cake 3.6

**Comment by saeideng** [comment]
and we should update min version probably 
https://github.com/cakephp/elastic-search/blob/fbc4df5a3106bcc727703b66d5c442fbcadcaa48/composer.json#L27
