### ISSUE TITLE
CakePHP 3.6 with Elasticsearch 5

### ISSUE THREAD

**Issue by SD-dthompson** [cakephp/elastic-search#183]
Is there a version/branch of this plugin that would be compatible with both CakePHP 3.6, and Elasticsearch Server version 5? In our case, elasticsearch server is version 5.6.8 and it hosts indexes for multiple sites, most of which are on versions of CakePHP before 3.6. We are just getting to the point where some will be moving to CakePHP 3.6, and the notes in the readme file for this plugin seem to suggest it's newest versions don't support Elasticsearch 5.x indexes. Is there some middle ground?

**Comment by lorenzo** [comment]
Yes, the `^2.0-RC1` version is what you want.

**Comment by lorenzo** [comment]
If I'm not mistaken, ES version 5 would work fine with that version

**Comment by SD-dthompson** [comment]
Great, Thank you!

**Comment by josbeir** [comment]
fyi RC2 and master also works ok with 5.x :-)
