### ISSUE TITLE
Argument 1 passed to Elastica\Client::setLogger() 

### ISSUE THREAD

**Issue by programadorwebfreelance** [cakephp/elastic-search#185]
Hi, when include the DataSource elastic in app.php show error:

Argument 1 passed to Elastica\Client::setLogger() must implement interface Psr\Log\LoggerInterface, instance of DebugKit\Database\Log\DebugLog given, ..... /vendor/cakephp/debug_kit/src/Panel/SqlLogPanel.php on line 68

CakePHP version 3.6.11.
ElasticSearch plugin - last versión.

**Comment by josbeir** [comment]
Please use the latest beta version of the plugin. This issue is fixed there

**Comment by markstory** [comment]
@josbeir should we promote that version to a stable release?

**Comment by josbeir** [comment]
@markstory you have my blessing ! ;-)
