### ISSUE TITLE
Console Commands and Helper classes

### ISSUE THREAD

**Issue by angelxmoreno** [cakephp/elastic-search#188]
Hello Bakers. I have been successfully using the plugin for a while and I have found myself feeling like some Console\Commands would be pretty useful. These are some of the classes/tools/helpers I've looking forward to see:

1. Service management
    - create:index
    - index:list
    - index:mapping
    - create:mapping based on some sort of mapping schema generated via bake with user modifications
    - index:table that paginates model data ( maybe via a finder ) and creates index documents 
2. baking
    - Index Classes based on existing index/types or cli flags
    - Document Classes based on existing mapping
    - Mapping schema based on Table schema
3. Auto index/deletions based on a Table Behavior

My original thought process was to make these features a separate plugin and have `cakephp/elastic-search` as a peer dependency. I would love to hear thoughts from the `cakephp/elastic-search` community on this.

**Comment by markstory** [comment]
I think those all sound like reasonable additions to this plugin. No need for an additional plugin.
