### ISSUE TITLE
Need configuration option for elasticsearch 6.5 only allowing one index

### ISSUE THREAD

**Issue by robertDawson2** [cakephp/elastic-search#191]
ElasticSearch 6.5 only allows one index, so when trying to run add and update, the type is automatically set to the index, but needs to be "_doc" for it to work correctly.
Being able to set the type in the config file would be ideal, in order to override this type.

**Comment by markstory** [comment]
Given the amount of breaking changes in ElasticSearch 6+ we might want to consider a major release of this plugin that doesn't attempt to save more than one type per index.

**Comment by robertDawson2** [comment]
> Given the amount of breaking changes in ElasticSearch 6+ we might want to consider a major release of this plugin that doesn't attempt to save more than one type per index.

I definitely think that overall, a major release raises a large need because of all the 6+ breaking changes, but I also recommend it here, as being able to "default" a type within the config file would be beneficial to lower version users as well.
