### ISSUE TITLE
phpunit ignoring fixture table.

### ISSUE THREAD

**Issue by agarzon** [cakephp/elastic-search#194]
I just noticed phpunit is ignoring the **$table** defined in fixture while running tests.

app.php
```php
        // Elastic
        'elastic' => [
            'className' => 'Cake\ElasticSearch\Datasource\Connection',
            'driver' => 'Cake\ElasticSearch\Datasource\Connection',
            'host' => 'elastic',
            'port' => 9200,
        ],
        'test_elastic' => [
            'className' => 'Cake\ElasticSearch\Datasource\Connection',
            'driver' => 'Cake\ElasticSearch\Datasource\Connection',
            'host' => 'elastic',
            'port' => 9200,
        ],
```

Fixture:

```php
    public $table = 'test_tournaments'; // this is where data should be collected on tests
    public $connection = 'test_elastic';
    public $schema = [....]
    public $records = [...]
```
While I run my phpunit tests, I can see the index **test_tournaments** is created, populated and deleted at the end in the elastic engine.... that is perfect.

I also have stored in the same engine another index containing the real data, called  **tournaments**

When I execute the tests, I should expect the model **Tournaments** to get data from the fixture data transparently, but is getting data from the  **tournaments** instead  **test_tournaments**, so whats the purpose of populating the fixture into elastic if the data wont be used in any tests?

BTW, this was working as expected in previous versions of this plugin.

Query code (example):
```php
IndexRegistry::get('Tournaments')->find('all')->first())
```
An easy and ugly workaround for me is modifying all my code to add conditions like:

```php
if (in_array(env('APPLICATION_ENV'), ['test'])) {
   IndexRegistry::get('Tournaments')->find('all')->first())
else {
   IndexRegistry::get('TestTournaments')->find('all')->first())
}
```
But that is not the idea behind fixtures and the code should not be adapted to satisfy tests. So I feel something is wrong here.

I'm not blaming this as a bug, chances are I'm doing something wrong but the lack of documentation makes hard time to get this straight and figuring ou how all work is just a test-fail adventure.

Someone else having this issue ?

**Comment by markstory** [comment]
Your fixture should be using `$table = tournaments`. The `table` option is for configuring the type name when it does not match the fixture class name for some reason.

You may need to run another/different elasticsearch instance if you want your application data to be uneffected by test suite operations as elasticsearch no longer has a simple way to namespace indexes with the same name.

**Comment by agarzon** [comment]
Thank you.

That was the other "solution" I did not mentioned. Isolating the data in different elastic engines.

But following that philosophy means **one elastic for only one index**. While in fact an elastic instance can store unlimited indexes, just like MySQL can have 'unlimited' databases and tables.

Also, in here we use docker instances, so will need to add an extra elastic instance only for testing which  means if lets say we have 10 developers, we gonna end having 20 elastic instances with all the resources consumption that it represent. 

I dont know if this changed because new elastic versions or the plugin updates but this was not needed in previous versions.

**Comment by markstory** [comment]
Older elastic search allowed multiple 'type's inside an 'index', but as of elasticsearch 6, each index can only have one type now.

>  But following that philosophy means **one elastic for only one index**. While in fact an elastic instance can store unlimited indexes, just like MySQL can have 'unlimited' databases and tables.

You can have multiple indexes per ES cluster they just need unique names. For example if your application has 3 different datatypes you don't need 3 clusters. Problems come up when you want to have multiple indexes with the same name, as you would need to have the same ES cluster handle test and non-test indexes.

It may be possible to add connection level 'prefixes' that each `Index` class appends to the conventions based name. That would allow you to have test/non-test connections share the same ES cluster. I personally don't have the time/need to add this feature but it sounds like you might :smile:

**Comment by agarzon** [comment]
I thought about the prefix based in the Datasources settings (like before we could assign the index name there), but I'm more a plugins 'consumer' than a contributor, I wish to have spare time to check the whole plugin code and see, but I don't have that time :disappointed: . I already started to play with our containers to add the extra one for testing.

Feel free to close this issue if doesn't contribute in the road map. Regards,
