### ISSUE TITLE
Call to undefined method Cake\ElasticSearch\Datasource\Connection::isQueryLoggingEnabled()

### ISSUE THREAD

**Issue by burzum** [cakephp/elastic-search#199]
Using CakePHP 3.7.7 and Debug Kit 3.18.0:

```
⟩ DebugKit\Panel\SqlLogPanel->initialize
ROOT\vendor\cakephp\debug_kit\src\ToolbarService.php, line 196
⟩ DebugKit\ToolbarService->initializePanels
ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
⟩ DebugKit\Middleware\DebugKitMiddleware->__invoke
CORE\src\Http\Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE\src\Http\Runner.php, line 51
⟩ Cake\Http\Runner->run
CORE\src\Http\Server.php, line 98
⟩ Cake\Http\Server->run
ROOT\webroot\index.php, line 33
```

The issue becomes even more funny because of this:

> Please use the 1.x branch if you are looking for a version of this plugin that is compatible with Cake versions prior to 3.6 and ES versions before 6.x (2.x and 5.x)

We can't use ES plugin 2.0 because we still use ES 2.x but can't use Cake 3.7.7 either. So this combination effectively nails us to 3.6...

Luckily we're about to merge the branch that is going to drop the Cake plugin in favour of directly using Elastica. Otherwise this would very likely force us to 3.6.

**Comment by markstory** [comment]
Are there changes that should be backported to the 1.x version of this project that would help improve this situation?

**Comment by burzum** [comment]
Probably yes, the issue didn't exist before. We'll merge our change this week and won't use this plugin anymore and I'm busy with other things, so I won't write any fixes / backports. Feel free to close this ticket or keep it open for other people who might run into the same situation.
