### ISSUE TITLE
Elastic search 7.x support

### ISSUE THREAD

**Issue by icex** [cakephp/elastic-search#204]
Could you create a development branch for Elastic Search 7.x? See my fork for initial 7.x support - https://github.com/icex/elastic-search

I had issues with the count() function in src/Query.php - it always returned 10.000 results max on our current project. So we upgraded to the latest Elastica and added $query->setParam('track_total_hits',true); to make it work as expected.

**Comment by markstory** [comment]
Could you open a pull request? That will be the quickest way for us to get your changes.

**Comment by icex** [comment]
here you go :) https://github.com/cakephp/elastic-search/pull/205
