### ISSUE TITLE
Bug in elastic search docs

### ISSUE THREAD

**Issue by rudy1976s** [cakephp/elastic-search#206]
In Cake book under elastic search doc the is a broken link :

https://github.com/cakephp/elastic-search/blob/master/src/FilterBuilder.php

**Comment by garas** [comment]
FilterBuilder was changed to QueryBuilder in 2.0.0 in https://github.com/cakephp/elastic-search/commit/fb9a129050ee0e81f9983a257df640c5b01e54c3.

Would you like to open PR to fix link and references?
