### ISSUE TITLE
No 3.0 Milestone

### ISSUE THREAD

**Issue by JacobAGTyler** [cakephp/elastic-search#213]
It would be great to get 3.0 with Cake4.x & Elastic Search 7.x ready for use. There doesn't seem to be a milestone for the 3.0 release and no individual bugs listed. It would be great to have a bit of a breakdown and all small bugs attached to the milestone, so it is clearer how to contribute.

**Comment by ADmad** [comment]
A `cake-4.x` branch has been started for Cake 4.x compatibility. There are no issues for it as no one has yet attempted updating it for ES 7 :)

**Comment by ADmad** [comment]
You can also help with the failing tests on #208.

**Comment by othercorey** [comment]
Closing as there is a 3.0 milestone and a cake-4.x branch.
