### ISSUE TITLE
How doc/book works?

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/elastic-search#239]
In my last merged PR, I put some extra examples and corrections on https://github.com/cakephp/elastic-search/blob/2.x/docs/pt/index.rst , but theses are not reflected on Cookbook.

They need any action to update?

Also, the version menu on Cookbook doesn't work for ElasticSearch plugin.

**Comment by markstory** [comment]
We have been having some problems with book deployments lately. I can restart the relevant jobs to get the latest changes deployed. 

Which link is incorrect in the book? Is it the sidebar link?

**Comment by markstory** [comment]
Elasticsearch book has been updated now.

**Comment by CauanCabral** [comment]
Thanks, just to register, I talking about that version menu on top (it's working now, but until yesterday, clicking on both version, redirect to the same URL/page):

![image](https://user-images.githubusercontent.com/83092/83141529-3caa8b80-a0c6-11ea-8370-7d5e2f392ad9.png)
