### ISSUE TITLE
Call to undefined method Elastica\Index::getType()

### ISSUE THREAD

**Issue by dynamonet** [cakephp/elastic-search#240]
Running on Cakephp 4, cakephp/elastic-search 3.1.1

 ```
  | protected function _execute()
  | {
  | $connection = $this->_repository->getConnection();
  | $index = $this->_repository->getName();
  | $type = **$connection->getIndex($index)->getType**($this->_repository->getType());
  |  
  | $query = $this->compileQuery();
  |  
  | return new ResultSet($type->search($query, $this->_searchOptions), $this);
```

Index::getTypes was removed in ruflin/elastica:7.1.1

**Comment by CauanCabral** [comment]
I think `cakephp/elastic-search` _3.1.x_ releases should support only `ruflin/elastica` _6.x_ versions.

`elastica` _7.0.0_ [are released only 23 days ago](https://github.com/ruflin/Elastica/releases/tag/7.0.0) and is not BC.

Can we start another major version to support it?
