### ISSUE TITLE
no such index [index: products]

### ISSUE THREAD

**Issue by ishan-biztech** [cakephp/elastic-search#244]
When accessing my `products/add` page it return "no such index [index: products]" error as shown in the screenshot

![Error_no_such_index_index_products_](https://user-images.githubusercontent.com/61005017/93092555-33691d00-f6bd-11ea-9c6c-2d41e2cd87c4.png)

**src/Controller/ProductsController.php:**
```php
public function add()
{
    $this->loadModel('Products', 'Elastic');

    $product = $this->Products->newEmptyEntity();
    if ($this->request->is('post')) {
        $product = $this->Products->patchEntity($product, $this->request->getData());
        if ($this->Products->save($product)) {
            $this->Flash->success(__('The product has been saved.'));

            return $this->redirect(['action' => 'index']);
        }
        $this->Flash->error(__('The product could not be saved. Please, try again.'));
    }
    $this->set(compact('product'));
}
```

**templates/Products/add.php**
```php
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Html->link(__('List Products'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="products form content">
            <?= $this->Form->create($product) ?>
            <fieldset>
                <legend><?= __('Add Product') ?></legend>
                <?php
                    echo $this->Form->control('name');
                    echo $this->Form->control('slug');
                    echo $this->Form->control('price');
                    echo $this->Form->control('description');
                    echo $this->Form->control('is_active');
                ?>
            </fieldset>
            <?= $this->Form->button(__('Submit')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>
```

I'm not searching or querying anything but want to add new index but I'm unable to access my view page. If I remove `$this->loadModel('Products', 'Elastic');` line from the controller, all works fine.

Am I missing something here?

**Comment by markstory** [comment]
Sounds like you're missing a Products index. FormHelper is trying to collect the mapping information for that index in order to build inputs using the correct types. You'll need to define the index and mapping for that to work.

**Comment by ishan-biztech** [comment]
Hey @markstory, thanks for the reply.

Yes, I understand that. But I do not want to map the products index since there is not Products index that's why I want to create a new index into the elasticsearch, as I've mentioned the url is http://myapp.test/products/add. This check is right if I am on edit page like http://myapp.test/products/edit/1, in this case only I want my inputs to map to the correct types.

What would you recommend should I do in this case?

**Comment by markstory** [comment]
> Yes, I understand that. But I do not want to map the products index since there is no Products index exists in elasticsearch, that's why I want to create a new index into the elasticsearch

I think we're getting tripped up on terminology here. When I say there is no 'products index' I mean that your elastic search instance does not have an index and mapping type defined. I get that you want to 'index products' (store them in elasticsearch). But in order to do that you need [to create an index](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html) and then [create a mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) to define the schema for your products index.
