### ISSUE TITLE
Connection does not fully implement ConnectionInterface

### ISSUE THREAD

**Issue by SparkyRih** [cakephp/elastic-search#248]
Cake\ElasticSearch\Datasource\Connection does not implement the following methods from ConnectionInterface.

- logQueries($enable = null);
- logger($instace = null);

This leads to a fatal error...

**Comment by markstory** [comment]
> This leads to a fatal error...

How do those fatal errors come up? Which version of this library are you using with which version of CakePHP?

**Comment by SparkyRih** [comment]
Sorry, I should've added that information right way:

CakePHP version: 3.9.6
Elasticsearch library: 6.7.2

But... now that I try to reproduce the error, it does not appear anymore (I was running CakePHP 3.6.*, I'm not sure anymore if the issue happend before or after upgrading).

**Comment by markstory** [comment]
Ok. If you're not able to reproduce anymore. We can close this issue until the problem comes up again.

**Comment by SparkyRih** [comment]
I'm back, I reproduced it by simply browsing to the web interface of the CakePHP application (have been working in the CLI for a while because of back-end processes):

`Error: Class Cake\ElasticSearch\Datasource\Connection contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Cake\Datasource\ConnectionInterface::logQueries, Cake\Datasource\ConnectionInterface::logger)
File /var/www/html/vendor/cakephp/elastic-search/src/Datasource/Connection.php
Line: 31`

**Comment by othercorey** [comment]
Can you give us the callstack?

**Comment by SparkyRih** [comment]
```
2021-02-15 12:35:01 Error: Fatal Error (1): Class Cake\ElasticSearch\Datasource\Connection contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Cake\Datasource\ConnectionInterface::logQueries, Cake\Datasource\ConnectionInterface::logger) in [/var/www/html/vendor/cakephp/elastic-search/src/Datasource/Connection.php, line 31]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 238
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 108
[main] - [internal], line ??



2021-02-15 12:35:01 Error: [Cake\Error\FatalErrorException] Class Cake\ElasticSearch\Datasource\Connection contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Cake\Datasource\ConnectionInterface::logQueries, Cake\Datasource\ConnectionInterface::logger) in /var/www/html/vendor/cakephp/elastic-search/src/Datasource/Connection.php on line 31
Stack Trace:
#0 /var/www/html/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(108): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class Cake\\Elas...', '/var/www/html/v...', 31)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


```

**Comment by garas** [comment]
What version of `cakephp/elastic-search` are you using? `2.x` or `3.x`?

`3.x` is for CakePHP 4, but there is no `composer.json` constraint to prevent incompatible version to be installed.

**Comment by SparkyRih** [comment]
So that might be the issue, since I'm using "cakephp/elastic-search": "^3.0"

**Comment by SparkyRih** [comment]
Yeah, that seems to be it, by downgrading cakephp/elastic-search to 2.0 the issue appears to be fixed...
