### ISSUE TITLE
Php 8 compatibility error

### ISSUE THREAD

**Issue by irongomme** [cakephp/elastic-search#249]
There is an error with PHP 8 : 
`Fatal error: Declaration of Cake\ElasticSearch\Query::_execute() must be compatible with Cake\Datasource\QueryTrait::_execute(): Cake\Datasource\ResultSetInterface in /var/www/vendor/cakephp/elastic-search/src/Query.php on line 621`

Which can fixed with in file /vendor/cakephp/elastic-search/src/Query.php (l621) : 
`protected function _execute(): \Cake\Datasource\ResultSetInterface`

**Comment by markstory** [comment]
No work has been done on this package to support PHP8. Would you like to help?

**Comment by othercorey** [comment]
I believe php 8 testing was disabled because it requires elasticsearch 7.

**Comment by irongomme** [comment]
Ok, so next step is to implement elastica 7.0, isn't it ?

**Comment by markstory** [comment]
> Ok, so next step is to implement elastica 7.0, isn't it ?

Sounds like it.

**Comment by JacobAGTyler** [comment]
Is this fixed by #252

**Comment by othercorey** [comment]
elastic-search 3.3.0 should resolve this.
