### ISSUE TITLE
Https with self-signed certificates

### ISSUE THREAD

**Issue by antonvolokha** [cakephp/elastic-search#253]
Does this plugin support https connection with self-signed certificates ?
Something like [this](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/connceting.html#_self_signed_certificates)

**Comment by markstory** [comment]
It should as long as elastica also supports self-signed certificates. See https://github.com/cakephp/elastic-search/blob/525fc698c6cb7793c796c2221e3c9d4bb3134ee2/src/Datasource/Connection.php#L84
