### ISSUE TITLE
BeforeFind event not triggered

### ISSUE THREAD

**Issue by zunnu** [cakephp/elastic-search#258]
Im using Elasticsearch 6 with version 2 of this plugin.
The beforefind event is not triggered. In my index I have.

```
public function beforeSave($event, $product, $options) {
    // triggered
}

public function beforeFind($event, $product, $options) {
    // not triggered
}
```

I looked at the code a bit and in the execute function there is event call for beforeFind. Should there be or am I missing something?
https://github.com/cakephp/elastic-search/blob/2.x/src/Query.php#L558

**Comment by markstory** [comment]
Looks like while we have `beforeFind` in the API docs we never actually implemented it.
