### ISSUE TITLE
CakePHP 4, AWS Elasticsearch 7 - The security token included in the request is invalid

### ISSUE THREAD

**Issue by morriesza** [cakephp/elastic-search#261]
So I'm running CakePHP 4 on an EC2 instance, AWS ES 7 and I've setup the ElasticSearch plugin in CakePHP.

`composer require cakephp/elastic-search "^3.0"`
I've added the elastic datasource connection in config/app.php

```
'elastic' => [
            'className' => 'Cake\ElasticSearch\Datasource\Connection',
            'driver' => 'Cake\ElasticSearch\Datasource\Connection',
            'host' => 'search-DOMAIN.REGION.es.amazonaws.com',
            'port' => 443,
            'transport' => "AwsAuthV4",
            'aws_access_key_id' => "KEY",
            'aws_secret_access_key' => "SECRET",
            'aws_region' => "REGION",
            'ssl' => 'true',
        ],
```
.. and I've activated the plugin

`use Cake\ElasticSearch\Plugin as ElasticSearchPlugin;`

```
class Application extends BaseApplication
{
    public function bootstrap()
    {
        $this->addPlugin(ElasticSearchPlugin::class);
```
I've manually added 1 index record to ES via curl from the EC2 instance. So I know the communication between EC2 and ES works.

`curl -XPUT -u 'KEY:SECRET' 'https://search-DOMAIN.REGION.es.amazonaws.com/movies?pretty' -d '{"director": "Burton, Tim", "genre": ["Comedy","Sci-Fi"], "year": 1996, "actor": ["Jack Nicholson","Pierce Brosnan","Sarah Jessica Parker"], "title": "Mars Attacks!"}' -H 'Content-Type: application/json'`
I also managed to search for this record via curl without any problems.

In the AppController.php I tried this simple search just to see if the plugin works and for the life of me, I can't get it to work.

```
# /src/Controller/AppController.php
...
use Cake\ElasticSearch\IndexRegistry;

class AppController extends Controller
{

    public function initialize(): void
    {
        parent::initialize();

        $this->loadModel('movies', 'Elastic');
        $query = $this->movies->find('all');
        $results = $query->toArray();
```
I'm getting the following error:

Client error: POST https://search-DOMAIN.REGION.es.amazonaws.com/movies/movies/_search resulted in a 403 Forbidden response: {"message":"The security token included in the request is invalid."} Elastica\Exception\Connection\GuzzleException

Seems like the plugin adds the 'Index' name twice for some reason. I looked everywhere for a setting that I might have missed. If I copy and paste the above URL and remove the duplicate Index from the URL in a browser it works fine.

https://search-DOMAIN.REGION.es.amazonaws.com/movies/_search
Am I missing something here?

I've even tried this method, and I get the same problem with duplicated index values in the url.

```
$Movies = IndexRegistry::get('movies');
$query = $Movies->find('all');
$results = $query->toArray();
```
I've tried a new/clean CakePHP instance and I get the same problem? Is there something wrong with the plugin? Is there a better approach to communicate with ES via CakePHP?

**Comment by markstory** [comment]
I've not used elasticsearch on AWS before, but would the extra path cause a 403 error? I would have expected elasticsearch to give a 404 if the the URL was not a valid one. Given that curl is working with basic authentication, perhaps you shouldn't be using the AwsAuthV4 transport as it does additional signing on requests, and should be using the http transport instead?

The additional path element should be fine as it specifies the mapping type inside the index. Our CI suite runs against elasticsearch 7.11.1 so reading and writing should work fine.
