### ISSUE TITLE
Cake4.4: Using a callable as a locator has been deprecated.

### ISSUE THREAD

**Issue by Lauwens** [cakephp/elastic-search#293]
On cake4.4 (and 5 in the future I assume) the Plugin.php generates a deprecation warning

Using a callable as a locator has been deprecated. Use an instance of Cake\Datasource\Locator\LocatorInterface instead

**Comment by markstory** [comment]
This was fixed on the 3.x branch but I forgot to create a release. The new 3.4.3 release should solve this problem.
