### ISSUE TITLE
example

### ISSUE THREAD

**Issue by MaxoMatos** [cakephp/elastic-search#5]
Could you write some example to use?
I would like to use mysql and ElasticSearch simultaneously.

**Comment by markstory** [comment]
I think we'd also need to finish this plugin before there are example. I think there will be more time to work on this once we get the 3.0.0 stable completed.

**Comment by darxmac** [comment]
I'm working on something similar, but for hooking into Azure mobile services REST API .. so some examples or hints on how you would use and implement this would be nice :)

**Comment by bravo-kernel** [comment]
Awesome!

**Comment by vttn** [comment]
I guess I will wait on using the plugin. A lot of documentation is missing. Using the cakephp Docs for this plugin is actually not a good idea at the moment. It would be best if there was a flag to say that it is not a good idea to use the docs.

**Comment by markstory** [comment]
@vttn Why isn't it a good idea to use the docs? What did you find missing from the docs?

**Comment by vttn** [comment]
How do I iterate over a query?

Given
```
$english_pages = TypeRegistry::get ( 'EnglishPages' );
$query = $english_pages->find ()
foreach($query as $row){
     debug($row); //empty output 
}

```

Dumping the data shows that the query was successul, and has a result.

```
var_dump (  $query->all ()->getResponse ()->getData () );
```

Gives

```
array (size=1)
  'message' => string '{"took":4,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"vashona_3","_type":"english_pages","_id":"23","_score":1.0,"_source":{
english_page_id: 23,
body: "<h1>Project</h1> <hr /> <p> means &#39;people&#39;.</p> <p>The Project is a content platform that aspires to unify &#39;s numerous dialects by providing a resource to those who find interest in the anguage for any reason.</p> <p>The lang'... (length=1611)
```

I think an example that gives a way to fetch a result will allow the community to expand on those examples and contribute to the Docs.

Thanks

**Comment by markstory** [comment]
Does your find() get any results? Both `$query->all()` and `$query->toArray()` should give access to the results. `all()` will provide a `ResultSet`, while `toArray()` will give an array.

**Comment by vttn** [comment]
```$query->toArray()``` returns an empty array

```$query->all()``` returns a result set https://gist.github.com/vttn/d81e203325f22c9b581b

```$query->all ()->getResponse ()->getData ()``` returns an array with index 'message' that contains a escaped json string https://gist.github.com/vttn/4192a827ca1438cb3d5a

**Comment by vttn** [comment]
@markstory thank you

**Comment by tum-sg15-stangl-anton** [comment]
@MaxoMatos I archieved the simultanious usage by implementing a new Behavior that overwrites the afterSave() method.
`    public function afterSave(Event $event, EntityInterface $entity, ArrayObject $options)
    {
        $elasticSearch = IndexRegistry::get($entity->getSource());
        $elasticSearch->save($entity);
    }`

Therefore a class that extends index from elasticsearch has to be implemented before.
