### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by rachid804** [cakephp/elastic-search#71]
I have two questions:
1. How can i get the max-score?
2. how can i configure a language analyzer like this: https://www.elastic.co/guide/en/elasticsearch/reference/1.4/analysis-lang-analyzer.html

**Comment by lorenzo** [comment]
About question 2: this plugin does not deal with index creation... please follow the instructions in the elastic search manual for creating indexes

**Comment by lorenzo** [comment]
On question 1: a max score of what?

**Comment by rachid804** [comment]
Thanks @lorenzo for your answer: 
1. When i use curl there is max-score of the search term in response like this:

```json
{
    "took": 114,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 0.032739405,
        "hits": [
            {
                "_index": "ibana_index",
                "_type": "words",
                "_id": "AVCoaGICdWeEYUSbhbJn",
                "_score": 0.032739405,
                "_source": {
                    "name": "....",
                    "description": "..."
                }
            }
        ]
    }
}
```

**Comment by lorenzo** [comment]
Check the api for the ResultSet, (the object returned after executing the query) https://github.com/cakephp/elastic-search/blob/master/src/ResultSet.php#L164

**Comment by rachid804** [comment]
Can you please give me a direction.
Thanks

**Comment by ADmad** [comment]
@rachid804 This is not a help forum. You can post a question on stackoverflow or join #cakphp IRC channel.

**Comment by rachid804** [comment]
Ok hanks @ADmad
