### ISSUE TITLE
Result from searching all indexes are not converted to documents

### ISSUE THREAD

**Issue by burzum** [cakephp/elastic-search#72]
As described [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-index-multi-type.html) you can search through all types like this:

`/_search` 

This can be done using the plugin by getting any type:

``` php
$type = TypeRegistry::get('Profiles');
$type->name('');
$results = $type->find()->all();
debug($resutls);
```

The problem with that is now that _all_ of the documents are of the type that belongs to the type class instance: Profiles.

But the elastic search result set contains the type information. I think the plugin should map the type based on that information to the correct document class.

**Comment by lorenzo** [comment]
That's actually by design. But this design choice is does not prevent having a mapper function casting to the right Document type if needed. If you want to implement this mapper, please let me know so that I can guide you.

**Comment by burzum** [comment]
> If you want to implement this mapper, please let me know so that I can guide you.

Please guide me. :)

**Comment by lorenzo** [comment]
You have two ways, but I think this way is the one that should be explored first:

* Add a `formatResults()` to your finder
* The formatter will `map()` each result
* The mapper will check the `type` of the document
* Use your own array to know the association `type_name => Type class` 
* Return `new $correctDocumentClass($oldDocument->_result)`; (You will need a getter for the _result property)

If that works correctly for you, we can formalize this process into the plugin

**Comment by burzum** [comment]
OK, thanks.

**Comment by burzum** [comment]
That's a hell of a workaround:

```php
		$query->formatResults(function (\Cake\ElasticSearch\ResultSet $results) {
			return $results->map(function ($row) {
				if (method_exists($row, 'getResult')) {
					$originalResult = $row->getResult();
					$resultType = $originalResult->getType();
					$resultType = Inflector::singularize($resultType);
					$resultType = Inflector::classify($resultType);
					$documentClass = \Cake\Core\App::className($resultType, 'Model/Document');
					if (class_exists($documentClass)) {
						$row = new $documentClass($originalResult->getData());
					}
				}
				return $row;
			});
		});
```

**Comment by lorenzo** [comment]
As I said before, the main challenge of this feature is having a way to map types form elastic search to type classes in PHP. I firmly thing that there should not be a magic solution for this, instead, it should probably be provided as a configuration parameter or function parameter when doing the find

**Comment by burzum** [comment]
If you do it inside the find it will become repetitive again. There should be a single place to put the mapping into. Also doing

```
$type = TypeRegistry::get('Profiles');
$type->name('');
```

feels somehow strange. The API is not very intuitive. I don't have a good idea how to improve this right now. Maybe adding a method to the query that gets a generic instance and configures it to search all types?

```php
$query->allTypes()->typeMap(['foo' => 'bar'])->where([/*...*/])->all();
```
