### ISSUE TITLE
Upgrade to Elastica 3.x

### ISSUE THREAD

**Issue by burzum** [cakephp/elastic-search#75]
Please see this issue https://github.com/ruflin/Elastica/pull/1016 and this PR  https://github.com/ruflin/Elastica/pull/1016

We're currently running into it and need to upgrade to 3.0.1 or convince them to do a 2.3.x release of Elastica. The plugin is nailing the versions down to ~2.2 right now.

**Comment by markstory** [comment]
What kind of breaking changes are in 3.x?

**Comment by ruflin** [comment]
@markstory Best is to check the [CHANGELOG](https://github.com/ruflin/Elastica/blob/master/CHANGELOG.md)

**Comment by markstory** [comment]
@burzum Looks like there are a few breaking changes that would effect us. If you wanted to lead the charge on updating the code around the breaking changes I'm sure we can get an upgrade merged in.

**Comment by Antoniossss** [comment]
This is definetly related to https://github.com/cakephp/elastic-search/issues/93.
Any plans for doing this ?

**Comment by lorenzo** [comment]
@Antoniossss check the 1.0 branch of this repo
