### ISSUE TITLE
`repository()->table()` does not exists in ElasticSearch\Type

### ISSUE THREAD

**Issue by markstory** [cakephp/elastic-search#76]
_From @ankr on January 15, 2016 11:43_

This is throws a fatal error, "undefined method table", when using the ElasticSearch plugin.

https://github.com/cakephp/cakephp/blob/master/src/Datasource/QueryTrait.php#L412

_Copied from original issue: cakephp/cakephp#8040_

**Comment by markstory** [comment]
Fixed in #78

**Comment by ankr** [comment]
Thank you! Sorry for the mispost.

**Comment by markstory** [comment]
Don't worry abot the mispost. It happens often and its simple for me to move tickets around.
