### ISSUE TITLE
TypeRegistry::get("Type") is not calling the initialize()

### ISSUE THREAD

**Issue by damianoporta** [cakephp/elastic-search#79]
Hello,
I was trying to load a behavior inside a type and i noticed that `initialize()` is not called when i load the **type** via `TypeRegistry::get('TypeName')`

**Comment by markstory** [comment]
Looks like we never added that. Whoops.

**Comment by markstory** [comment]
Pull request up now.

**Comment by damianoporta** [comment]
looks ok to me, can we merge? I need it! :D

**Comment by markstory** [comment]
@damianoporta Merged, I'll do a release tonight.

**Comment by damianoporta** [comment]
@markstory awesome! Thank you so much.
