### ISSUE TITLE
how to implement match_phrase_prefix query ?

### ISSUE THREAD

**Issue by damianoporta** [cakephp/elastic-search#81]
Hello,
I should use **match_phrase_prefix** (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html)

it seems not implemented here, at the moment i am testing the query with this json:

```
{  
   "fields":[  
      "name"
   ],
   "query":{  
      "match_phrase_prefix":{  
         "name":{  
            "query":"test",
            "slop":3
         }
      }
   }
}
```
how should i build this query? Thanks!

**Comment by markstory** [comment]
I think for now you'd have to directly set the query using `$query->query()`

**Comment by damianoporta** [comment]
This is the solution:

```
$query->query(new \Elastica\Query\MatchPhrasePrefix('fullname', ['query' => $args['fullname'], 'slop' => 2]));
```
