### ISSUE TITLE
No callbacks are called

### ISSUE THREAD

**Issue by dario86** [cakephp/elastic-search#84]
Hi, I have this code in my controller:

```php
public function formStupido()
{
        $Companies = TypeRegistry::get('Companies.Companies');
        $companies = $Companies->newEntity(['name' => 'ciao']);
        $savedCompany = $Companies->save($companies);
}
```

This is my CompaniesType in plugin Companies:

```php
<?php
namespace Companies\Model\Type;

use Cake\ElasticSearch\Type;
use Cake\ElasticSearch\Query;
use Cake\ElasticSearch\FilterBuilder;
use App\Lib\FileUpload;

class CompaniesType extends Type
{
    /**
     * initialize method
     * 
     * @param array $config
     */
    public function initialize(array $config)
    {
     
    }
    
    public function beforeMarshal(Event $event, ArrayObject $data, ArrayObject $options)
    {
        debug('marshaller');
        exit();
    }
    
    public function beforeSave(Event $event, ArrayObject $data, ArrayObject $options)
    {
        debug('before');
        exit();
    }
}
?>
```

Document is created and no callbacks are called

**Comment by damianoporta** [comment]
same here!

**Comment by josegonzalez** [comment]
@markstory I know you're not a fan of adding behavior support because some behaviors may be incompatible, but couldn't the same thing be said about a behavior targeting a specific database? For instance, I could write something that targeted a specific column type only available to postgres. I don't see why we can't put a big fat caveat on this plugin and say certain core behaviors are not expected to work (or make them work).

**Comment by markstory** [comment]
>  I don't see why we can't put a big fat caveat on this plugin and say certain core behaviors are not expected to work (or make them work).

Outside of the TimestampBehavior, I'm not sure _any_ of the core behaviors work.

**Comment by markstory** [comment]
Looks like we never implemented the default callback binding, for `Type`. I'll add that in.

**Comment by josegonzalez** [comment]
@markstory how difficult would it be to test that? Why do you think they wouldn't work?

**Comment by markstory** [comment]
Pull request up now.

**Comment by markstory** [comment]
@josegonzalez I don't think the others would work based on how they are implemented. TreeBehavior, CounterCache and TranslateBehavior rely on association methods that do not exist in elasticsearch.
