### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by gieart87** [cakephp/elastic-search#86]
I had a problem about pagination in elastic . I try to send a parameter "?page = 2" when using mysql running normally . But when using elastic it does not work .

```
{
    "message": "Not Found",
    "url": "\/myapp\/api\/categories.json?limit=3\u0026amp;page=2",
    "code": 404,
    "trace": [
        {
            "file": "\/var\/www\/html\/myapp\/vendor\/cakephp\/cakephp\/src\/Controller\/Controller.php",
            "line": 688,
            "function": "paginate",
            "class": "Cake\\Controller\\Component\\PaginatorComponent",
            "type": "-\u003E",
            "args": [
                {

                },
                {
                    "limit": 3
                }
            ]
        },
        {`
```

**Comment by markstory** [comment]
What is the `-\u003E` doing in there?

**Comment by gieart87** [comment]
That is debug trace of cakephp , I do not know what causes it
![elastic](https://cloud.githubusercontent.com/assets/145084/13231491/afcc115c-d9dc-11e5-9f05-175ee3230602.png)

**Comment by markstory** [comment]
Ok. Is there anything more to that trace?

**Comment by gieart87** [comment]
This is the full trace :

`{
    "message": "Not Found",
    "url": "/bot/viglink/cakeviglink/api/categories.json?page=2",
    "code": 404,
    "trace": [
        {
            "file": "/var/www/html/bot/viglink/cakeviglink/vendor/cakephp/cakephp/src/Controller/Controller.php",
            "line": 688,
            "function": "paginate",
            "class": "Cake\\Controller\\Component\\PaginatorComponent",
            "type": "->",
            "args": [
                {},
                {
                    "limit": 3
                }
            ]
        },
        {
            "file": "/var/www/html/bot/viglink/cakeviglink/src/Controller/Api/CategoriesController.php",
            "line": 39,
            "function": "paginate",
            "class": "Cake\\Controller\\Controller",
            "type": "->",
            "args": [
                {}
            ]
        },
        {
            "file": "/var/www/html/bot/viglink/cakeviglink/vendor/cakephp/cakephp/src/Controller/Controller.php",
            "line": 429,
            "function": "call_user_func_array",
            "args": [
                [
                    {
                        "components": {
                            "RequestHandler": null
                        },
                        "name": "Categories",
                        "helpers": [],
                        "request": {
                            "params": {
                                "plugin": null,
                                "controller": "Categories",
                                "action": "index",
                                "_ext": "json",
                                "pass": [],
                                "_method": "GET",
                                "prefix": "api",
                                "isAjax": false,
                                "paging": {
                                    "categories": {
                                        "finder": "all",
                                        "page": 1,
                                        "current": 3,
                                        "count": 3,
                                        "perPage": 3,
                                        "prevPage": false,
                                        "nextPage": false,
                                        "pageCount": 1,
                                        "sort": null,
                                        "direction": false,
                                        "limit": null,
                                        "sortDefault": false,
                                        "directionDefault": false
                                    }
                                }
                            },
                            "data": [],
                            "query": {
                                "page": "2"
                            },
                            "cookies": [],
                            "url": "api/categories.json",
                            "base": "/bot/viglink/cakeviglink",
                            "webroot": "/bot/viglink/cakeviglink/",
                            "here": "/bot/viglink/cakeviglink/api/categories.json",
                            "trustProxy": false
                        },
                        "response": {},
                        "paginate": {
                            "limit": 3
                        },
                        "autoRender": true,
                        "View": null,
                        "plugin": null,
                        "passedArgs": [],
                        "modelClass": "Categories",
                        "viewClass": null,
                        "viewVars": [],
                        "RequestHandler": {
                            "enabled": true,
                            "response": {},
                            "ext": "json",
                            "request": {
                                "params": {
                                    "plugin": null,
                                    "controller": "Categories",
                                    "action": "index",
                                    "_ext": "json",
                                    "pass": [],
                                    "_method": "GET",
                                    "prefix": "api",
                                    "isAjax": false,
                                    "paging": {
                                        "categories": {
                                            "finder": "all",
                                            "page": 1,
                                            "current": 3,
                                            "count": 3,
                                            "perPage": 3,
                                            "prevPage": false,
                                            "nextPage": false,
                                            "pageCount": 1,
                                            "sort": null,
                                            "direction": false,
                                            "limit": null,
                                            "sortDefault": false,
                                            "directionDefault": false
                                        }
                                    }
                                },
                                "data": [],
                                "query": {
                                    "page": "2"
                                },
                                "cookies": [],
                                "url": "api/categories.json",
                                "base": "/bot/viglink/cakeviglink",
                                "webroot": "/bot/viglink/cakeviglink/",
                                "here": "/bot/viglink/cakeviglink/api/categories.json",
                                "trustProxy": false
                            },
                            "components": []
                        },
                        "Flash": {
                            "request": {
                                "params": {
                                    "plugin": null,
                                    "controller": "Categories",
                                    "action": "index",
                                    "_ext": "json",
                                    "pass": [],
                                    "_method": "GET",
                                    "prefix": "api",
                                    "isAjax": false,
                                    "paging": {
                                        "categories": {
                                            "finder": "all",
                                            "page": 1,
                                            "current": 3,
                                            "count": 3,
                                            "perPage": 3,
                                            "prevPage": false,
                                            "nextPage": false,
                                            "pageCount": 1,
                                            "sort": null,
                                            "direction": false,
                                            "limit": null,
                                            "sortDefault": false,
                                            "directionDefault": false
                                        }
                                    }
                                },
                                "data": [],
                                "query": {
                                    "page": "2"
                                },
                                "cookies": [],
                                "url": "api/categories.json",
                                "base": "/bot/viglink/cakeviglink",
                                "webroot": "/bot/viglink/cakeviglink/",
                                "here": "/bot/viglink/cakeviglink/api/categories.json",
                                "trustProxy": false
                            },
                            "response": {},
                            "components": []
                        },
                        "Categories": {},
                        "Paginator": {
                            "request": {
                                "params": {
                                    "plugin": null,
                                    "controller": "Categories",
                                    "action": "index",
                                    "_ext": "json",
                                    "pass": [],
                                    "_method": "GET",
                                    "prefix": "api",
                                    "isAjax": false,
                                    "paging": {
                                        "categories": {
                                            "finder": "all",
                                            "page": 1,
                                            "current": 3,
                                            "count": 3,
                                            "perPage": 3,
                                            "prevPage": false,
                                            "nextPage": false,
                                            "pageCount": 1,
                                            "sort": null,
                                            "direction": false,
                                            "limit": null,
                                            "sortDefault": false,
                                            "directionDefault": false
                                        }
                                    }
                                },
                                "data": [],
                                "query": {
                                    "page": "2"
                                },
                                "cookies": [],
                                "url": "api/categories.json",
                                "base": "/bot/viglink/cakeviglink",
                                "webroot": "/bot/viglink/cakeviglink/",
                                "here": "/bot/viglink/cakeviglink/api/categories.json",
                                "trustProxy": false
                            },
                            "response": {},
                            "components": []
                        }
                    },
                    "index"
                ],
                []
            ]
        },
        {
            "file": "/var/www/html/bot/viglink/cakeviglink/vendor/cakephp/cakephp/src/Routing/Dispatcher.php",
            "line": 114,
            "function": "invokeAction",
            "class": "Cake\\Controller\\Controller",
            "type": "->",
            "args": []
        },
        {
            "file": "/var/www/html/bot/viglink/cakeviglink/vendor/cakephp/cakephp/src/Routing/Dispatcher.php",
            "line": 87,
            "function": "_invoke",
            "class": "Cake\\Routing\\Dispatcher",
            "type": "->",
            "args": [
                {
                    "components": {
                        "RequestHandler": null
                    },
                    "name": "Categories",
                    "helpers": [],
                    "request": {
                        "params": {
                            "plugin": null,
                            "controller": "Categories",
                            "action": "index",
                            "_ext": "json",
                            "pass": [],
                            "_method": "GET",
                            "prefix": "api",
                            "isAjax": false,
                            "paging": {
                                "categories": {
                                    "finder": "all",
                                    "page": 1,
                                    "current": 3,
                                    "count": 3,
                                    "perPage": 3,
                                    "prevPage": false,
                                    "nextPage": false,
                                    "pageCount": 1,
                                    "sort": null,
                                    "direction": false,
                                    "limit": null,
                                    "sortDefault": false,
                                    "directionDefault": false
                                }
                            }
                        },
                        "data": [],
                        "query": {
                            "page": "2"
                        },
                        "cookies": [],
                        "url": "api/categories.json",
                        "base": "/bot/viglink/cakeviglink",
                        "webroot": "/bot/viglink/cakeviglink/",
                        "here": "/bot/viglink/cakeviglink/api/categories.json",
                        "trustProxy": false
                    },
                    "response": {},
                    "paginate": {
                        "limit": 3
                    },
                    "autoRender": true,
                    "View": null,
                    "plugin": null,
                    "passedArgs": [],
                    "modelClass": "Categories",
                    "viewClass": null,
                    "viewVars": [],
                    "RequestHandler": {
                        "enabled": true,
                        "response": {},
                        "ext": "json",
                        "request": {
                            "params": {
                                "plugin": null,
                                "controller": "Categories",
                                "action": "index",
                                "_ext": "json",
                                "pass": [],
                                "_method": "GET",
                                "prefix": "api",
                                "isAjax": false,
                                "paging": {
                                    "categories": {
                                        "finder": "all",
                                        "page": 1,
                                        "current": 3,
                                        "count": 3,
                                        "perPage": 3,
                                        "prevPage": false,
                                        "nextPage": false,
                                        "pageCount": 1,
                                        "sort": null,
                                        "direction": false,
                                        "limit": null,
                                        "sortDefault": false,
                                        "directionDefault": false
                                    }
                                }
                            },
                            "data": [],
                            "query": {
                                "page": "2"
                            },
                            "cookies": [],
                            "url": "api/categories.json",
                            "base": "/bot/viglink/cakeviglink",
                            "webroot": "/bot/viglink/cakeviglink/",
                            "here": "/bot/viglink/cakeviglink/api/categories.json",
                            "trustProxy": false
                        },
                        "components": []
                    },
                    "Flash": {
                        "request": {
                            "params": {
                                "plugin": null,
                                "controller": "Categories",
                                "action": "index",
                                "_ext": "json",
                                "pass": [],
                                "_method": "GET",
                                "prefix": "api",
                                "isAjax": false,
                                "paging": {
                                    "categories": {
                                        "finder": "all",
                                        "page": 1,
                                        "current": 3,
                                        "count": 3,
                                        "perPage": 3,
                                        "prevPage": false,
                                        "nextPage": false,
                                        "pageCount": 1,
                                        "sort": null,
                                        "direction": false,
                                        "limit": null,
                                        "sortDefault": false,
                                        "directionDefault": false
                                    }
                                }
                            },
                            "data": [],
                            "query": {
                                "page": "2"
                            },
                            "cookies": [],
                            "url": "api/categories.json",
                            "base": "/bot/viglink/cakeviglink",
                            "webroot": "/bot/viglink/cakeviglink/",
                            "here": "/bot/viglink/cakeviglink/api/categories.json",
                            "trustProxy": false
                        },
                        "response": {},
                        "components": []
                    },
                    "Categories": {},
                    "Paginator": {
                        "request": {
                            "params": {
                                "plugin": null,
                                "controller": "Categories",
                                "action": "index",
                                "_ext": "json",
                                "pass": [],
                                "_method": "GET",
                                "prefix": "api",
                                "isAjax": false,
                                "paging": {
                                    "categories": {
                                        "finder": "all",
                                        "page": 1,
                                        "current": 3,
                                        "count": 3,
                                        "perPage": 3,
                                        "prevPage": false,
                                        "nextPage": false,
                                        "pageCount": 1,
                                        "sort": null,
                                        "direction": false,
                                        "limit": null,
                                        "sortDefault": false,
                                        "directionDefault": false
                                    }
                                }
                            },
                            "data": [],
                            "query": {
                                "page": "2"
                            },
                            "cookies": [],
                            "url": "api/categories.json",
                            "base": "/bot/viglink/cakeviglink",
                            "webroot": "/bot/viglink/cakeviglink/",
                            "here": "/bot/viglink/cakeviglink/api/categories.json",
                            "trustProxy": false
                        },
                        "response": {},
                        "components": []
                    }
                }
            ]
        },
        {
            "file": "/var/www/html/bot/viglink/cakeviglink/webroot/index.php",
            "line": 37,
            "function": "dispatch",
            "class": "Cake\\Routing\\Dispatcher",
            "type": "->",
            "args": [
                {
                    "params": {
                        "plugin": null,
                        "controller": "Categories",
                        "action": "index",
                        "_ext": "json",
                        "pass": [],
                        "_method": "GET",
                        "prefix": "api",
                        "isAjax": false,
                        "paging": {
                            "categories": {
                                "finder": "all",
                                "page": 1,
                                "current": 3,
                                "count": 3,
                                "perPage": 3,
                                "prevPage": false,
                                "nextPage": false,
                                "pageCount": 1,
                                "sort": null,
                                "direction": false,
                                "limit": null,
                                "sortDefault": false,
                                "directionDefault": false
                            }
                        }
                    },
                    "data": [],
                    "query": {
                        "page": "2"
                    },
                    "cookies": [],
                    "url": "api/categories.json",
                    "base": "/bot/viglink/cakeviglink",
                    "webroot": "/bot/viglink/cakeviglink/",
                    "here": "/bot/viglink/cakeviglink/api/categories.json",
                    "trustProxy": false
                },
                {}
            ]
        }
    ]
}`

**Comment by markstory** [comment]
I guess my next dumb question is are there more than 1 page of results in elastic search?

**Comment by markstory** [comment]
Ok. I'll take a look and try to reproduce locally.

**Comment by gieart87** [comment]
haven't any update yet, @markstory ?

**Comment by markstory** [comment]
@gieart87 No, I've not had a chance to look at this yet.
