### ISSUE TITLE
Search documents without specifying a column

### ISSUE THREAD

**Issue by vttn** [cakephp/elastic-search#87]
How can I search documents without specifying a column i.e.

     _search?q=Foo

I tried 

    $this->Businesses->find('all')->where(['*'=>'Foo']);

Thanks

**Comment by lorenzo** [comment]
Use the _all column

**Comment by vttn** [comment]
```
$q = 'Foo';
$businesses = $this->Businesses->find('all')->where(function ($builder) use($q) {
            return $builder->query(new \Elastica\Query\SimpleQueryString($q));
        }); 
```

gives a acts more like _search/?q=Foo
