### ISSUE TITLE
Client ignores "log=>true" in config and $logQueries field is never set 

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/elastic-search#91]
There is not place where Cake\ElasticSearch\Datasource\Connection#logQueries is set to the value of $config['log'] causing no way to enable request logging.One way would be to add proper conditional in the contructor as it is done for 'name'

```
    public function __construct(array $config = [], $callback = null)
    {
        $config += ['index' => '_all'];
        if (isset($config['name'])) {
            $this->configName = $config['name'];
        }
        parent::__construct($config, $callback);
    }
```

**Comment by markstory** [comment]
Pull request up now.
