### ISSUE TITLE
Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) 

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/elastic-search#93]
I have ran into the following error message
`Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) `

Seems like related to underlying dependency bug https://github.com/ruflin/Elastica/issues/970.
Probably switching to 3.1.1 client would fix the issue

**Comment by markstory** [comment]
Closing as a pull request is open now.
