### ISSUE TITLE
How to implement the suggest API the best?

### ISSUE THREAD

**Issue by burzum** [cakephp/elastic-search#99]
How can I implement the suggest feature of ES the best using the plugin? Any guidance on this please?

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-suggesters-completion.html

**Comment by markstory** [comment]
Which parts? There are both indexing and query parts to the suggesters.

**Comment by burzum** [comment]
@markstory the suggesters.

@jippi is the plugin finally supporting an ES version above 1.7? We've used 1.7 mostly because the Cake plugin or the underlying Elastica lib was stuck with this version.

**Comment by lorenzo** [comment]
@burzum yes, branch 1.0 of this plugin supports elastic 2

**Comment by burzum** [comment]
@lorenzo OK, any direction on how to use the suggest feature with it?

**Comment by lorenzo** [comment]
Maybe look how it can be done with elastica... If there is no easy way of calling the elastica methods within this plugin, we can just added it.
